### ISSUE TITLE
Is there a suggested configuration for a newb?

### ISSUE THREAD

**Issue by lucasgonze** [tomhiggins/anyfesto#15]
I want to put an Anyfesto box in my office to serve the park across the street, a range of about 100 yards. I won't use it for anything but this purpose.

Suggestions on the RPI configuration?

I'm aiming to spend $50 or less.

**Comment by tomhiggins** [comment]
A Raspberry Pi with an external antenna Wi-Fi nic [1] would work. Depending on local wifi saturation you might need to resort to a directional guide.[2] 

[1] https://www.adafruit.com/product/1030
[2] http://www.freeantennas.com/projects/template/index.html
Or
http://www.neodux.com/read/Cantenna%20w/%20Funnel

**Comment by lucasgonze** [comment]
Also related:
https://github.com/tomhiggins/anyfesto/blob/master/hardware/readme.txt
