### ISSUE TITLE
How does one discover an Anyfesto box, anyways?

### ISSUE THREAD

**Issue by Kevin-Prichard** [tomhiggins/anyfesto#16]
I get that it's a webserver, audio server, etc.

But how do you discover that one nearby you??

**Comment by tomhiggins** [comment]
In the wild, scan wifi SSIDs. 
In a group setting, ask coordinators or fellow participants if they are running or know of someone running one.
If you are an organizer I would suggest using signs, audio, word of mouth, pre event press to let folks know the SSID to join.
