### ISSUE TITLE
any update on the automated install script?

### ISSUE THREAD

**Issue by NIXOYE** [tomhiggins/anyfesto#2]
Would be nice to have this for installation on a fresh C.H.I.P

**Comment by tomhiggins** [comment]
I am aiming for work on the install scripts over the Winter Holidays. I order a few more CHIPS to do some testing as the one I have has been pressed into service as a backpack wandering Anyfesto install. Check back in the first week of Jan and if nothing has been done please shoot me a msg.

**Comment by NIXOYE** [comment]
Ok, sounds good. Btw do you know if there is a way for people to access the
services by just connecting to the wifi workout having to ssh/telnet in? I
feel lol that makes a  huge difference in ease of use. As smartphones don't
come with the ability to ssh without a 3rd party app

**Comment by NIXOYE** [comment]
also, itd be nice if auto install script also could optionally setup cjdns and a way to use a chip as a smart firewall for your home to connect iot devices to

**Comment by NIXOYE** [comment]
@tomhiggins its the first week of january so im checking in

**Comment by arkgit** [comment]
paging @tomhiggins

**Comment by tomhiggins** [comment]
Hello fawlks. Holiday crazy season took me away from the work, but progress now is being eeked out. 
I am testing a NonPiratebox version of Anyfesto. I love Piratebox and all the folks who work on it but I want Anyfesto to work even if they make changes upstream. Check out the recent commits.
Also, if I can make it all go tick tick tick I will do up a video walk thru of the install on the CHIP and hopefully have a script ready to make it automagic as possible. 
Thanks for your interest in this. Stay tuned .
-tom

**Comment by tomhiggins** [comment]
All fixed, try the updated CHIP install.
