### ISSUE TITLE
installPI "bash PIinstall.sh" does not match "PIInstall.sh

### ISSUE THREAD

**Issue by PeterTGarner** [tomhiggins/anyfesto#4]
wget --no-check-certificate  https://raw.githubusercontent.com/tomhiggins/anyfesto/master/deployables/current/PIinstall.sh
bash PIinstall.sh

Should be 
wget --no-check-certificate  https://raw.githubusercontent.com/tomhiggins/anyfesto/master/deployables/current/PIInstall.sh
bash PIInstall.sh

**Comment by tomhiggins** [comment]
Thanks for the correction! Will fold it in. 

-tom

**Comment by tomhiggins** [comment]
Fixed.
