### ISSUE TITLE
Problem trying to execute the installer

### ISSUE THREAD

**Issue by yeyeto2788** [tomhiggins/anyfesto#5]
Hey there! Great project.

I tried installing everything from the `CHIPinstaller.sh` and the first installed was terrible since it didn't take the files from your repository due to a missing or false certificate here I have attached the logs.
[installationAnyfesto.txt](https://github.com/tomhiggins/anyfesto/files/1204346/installationAnyfesto.txt)

In order to get the files I have modified the `CHIPinstaller.sh` where it had the `wget` command to `wget --no-check-certificate` and it seems to be installed on the CHIP.

After two reboot it showed the AP on my phone and I can see the site.

Regards

**Comment by tomhiggins** [comment]
Thanks for the report.  I will give this a testing and get --no-check-certificate into the script.

**Comment by yeyeto2788** [comment]
Hey there! 

This I guess it was a problem on my C.H.I.P since I had the time not set properly.  I run the command `date -R` and it gave me back a time to those old days (something like: **1 JAN 1970 00:00:00**).

And the other problem was about the `ca-certificates`.

Here you have what I did in order to clone the repositories with no problem in case you want to create a FAQ section.

**ERROR**
```
fatal: unable to access 'https://github.com/<user>/<repository>.git/': server certificate verification failed. CAfile: /etc/ssl/certs/ca-certificates.crt CRLfile: nonep
```

* **SOLUTION 1**
  `sudo update-ca-certificates`

* **SOLUTION 2**
  If previous solution didn't work follow the steps below
  * Configure your time zone:
    `sudo dpkg-reconfigure tzdata`
    * Select you time zone you want to set for the system
  * Install `ntp`
    `sudo apt-get install -y ntp`
  * Check if ntp is working by:
    `ntpq -P` or `sudo ntpq -P` it should show something like this:
    ```
      remote           refid      st t when poll reach   delay   offset  jitter
      ==============================================================================
      ntp.redimadrid. .INIT.          16 u    -   64    0    0.000    0.000   0.000
      x.ns.gin.ntt.ne .INIT.          16 u    -   64    0    0.000    0.000   0.000
      85.254.217.235  .INIT.          16 u    -   64    0    0.000    0.000   0.000
    ```
    **NOTE:** Take into account I have setup Spain as my time zone.

    If this doesn't show anything or you get something like `No association ID's returned` then type `dpkg-reconfigure ntp` or `sudo dpkg-reconfigure ntp`
  * Add current time to system by:
    `date -s "22 AUG 2017 13:10:00"`

**Comment by tomhiggins** [comment]
Thank you for documenting that. 
Yes, a Trouble Shooting/FAQ is probably a good idea . I will get it on the todo list.
