### ISSUE TITLE
Possible way to remove the previous internet access

### ISSUE THREAD

**Issue by yeyeto2788** [tomhiggins/anyfesto#6]
Hey! me again.

Before running the installer (`CHIPinstaller.sh`) on the CHIP I connect through `sudo nmtui` command and after installation was done I got this message: 
```
-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_
Installation Complete...Preparing To Reboot
-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_
Press any key to reboot the CHIP.
sudo: unable to resolve host chip
sudo: unable to resolve host chip
Created symlink from /etc/systemd/system/multi-user.target.wants/vlc.service to /etc/systemd/system/vlc.service.
sudo: unable to resolve host chip
Created symlink from /etc/systemd/system/multi-user.target.wants/kiwix.service to /etc/systemd/system/kiwix.service.
sudo: unable to resolve host chip
Created symlink from /etc/systemd/system/multi-user.target.wants/kiwiirc.service to /etc/systemd/system/kiwiirc.service.
sudo: unable to resolve host chip
sudo: unable to resolve host chip
sudo: unable to resolve host chip
sudo: unable to resolve host chip
sudo: unable to resolve host chip
Error: unknown connection: Sant
Error: cannot delete unknown connection(s): 'Sant'.
sudo: unable to resolve host chip
sudo: unable to resolve host chip
sudo: unable to resolve host chip
sudo: unable to resolve host chip
sudo: unable to resolve host chip
```
Note the part where is says **`Error: cannot delete unknown connection(s): 'Sant'.`**
Might it be due to having blank space on the name of the SSID?

Is there a way to solve this?
Regards.

**Comment by tomhiggins** [comment]
I recently redid the order of operation for setting up the new network to avoid the host name change messing up the reboot. 
My go to fix is to flash the CHIP fresh and redo the install with the newest install sh. 
Let me know if that fixes it for you. 
As for spaces in SSID, I try to avoid spaces in places like this as sometimes it causes  connections to go splat. Most times not and it may be me supposing mythology on experience...but to be safe I keep it  to no spaces.

**Comment by yeyeto2788** [comment]
Just to double check, what version did you flash on your C.H.I.P?

I did a GUI 4.4 and then a Server 4.4 and that's when my Serial connection broke. I'll give it a try to the new installer.

Regards and thanks for your reply!

**Comment by tomhiggins** [comment]
I tend to keep to the Server 4.4 as it leaves a bit more room in memory.

**Comment by yeyeto2788** [comment]
Hey there! 

I did try the installer from a fresh install of Server 4.4 it worked perfectly as per installation process.

What I did to remove the wifi connection with spaces on the name was with the command
**`sudo nmtui`** from it you can delete the connection on the **`edit connection`** option and then delete.

I'll close this issue since it is a minor issue that it is already solve and also has a quick fix.

Regards
