### ISSUE TITLE
USB to Serial connection broken after executing installer

### ISSUE THREAD

**Issue by yeyeto2788** [tomhiggins/anyfesto#7]
Hello there! 

I have discovered that after rebooting the CHIP two times after installing all needed software trough `CHIPinstaller.sh` I cannot reconnect to the CHIP via putty and I can hear and see on the Device Manager that the CHIP is connecting and reconnecting to the computer.

Has this happened to you previously?

Regards.

**Comment by tomhiggins** [comment]
I have not had this happen on my CHIP installs. I will try to see if I can recreate the issue. 
Not a fix but you can SSH into your AnyfestoCHIP from any device you connect to it via wifi.

**Comment by yeyeto2788** [comment]
You're totally right. At that moment I was trying to connect via USB-Serial and just so you know. Maybe it could has happened to you.

I'll give it a try to the new installer and I'll let you know if I get the same error.

Regards.

**Comment by tomhiggins** [comment]
Thanks. I have not had a chance to try and force this issue. Weekend hopefully will have a bit of free time in it for me to test.

**Comment by yeyeto2788** [comment]
Hey there! 

Serial connection is back after installing and doing a second reboot. I guess that I have done something wrong to it.

Regards.
